// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/rhizome_atlas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory where holon.mod will be created.
	Directory string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	// The holon path (e.g. "github.com/org/myholon").
	HolonPath     string `protobuf:"bytes,2,opt,name=holon_path,json=holonPath,proto3" json:"holon_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *InitRequest) GetHolonPath() string {
	if x != nil {
		return x.HolonPath
	}
	return ""
}

type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the created holon.mod file.
	ModFile       string `protobuf:"bytes,1,opt,name=mod_file,json=modFile,proto3" json:"mod_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetModFile() string {
	if x != nil {
		return x.ModFile
	}
	return ""
}

type AddRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory containing holon.mod.
	Directory string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	// Dependency path (e.g. "github.com/org/dep").
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Semantic version (e.g. "v1.2.0").
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{2}
}

func (x *AddRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *AddRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AddResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The dependency as recorded.
	Dependency    *Dependency `protobuf:"bytes,1,opt,name=dependency,proto3" json:"dependency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{3}
}

func (x *AddResponse) GetDependency() *Dependency {
	if x != nil {
		return x.Dependency
	}
	return nil
}

type RemoveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory containing holon.mod.
	Directory string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	// Dependency path to remove.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{5}
}

type PullRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory containing holon.mod.
	Directory     string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{6}
}

func (x *PullRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type PullResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dependencies that were fetched or verified.
	Fetched       []*Dependency `protobuf:"bytes,1,rep,name=fetched,proto3" json:"fetched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{7}
}

func (x *PullResponse) GetFetched() []*Dependency {
	if x != nil {
		return x.Fetched
	}
	return nil
}

type VerifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory containing holon.mod and holon.sum.
	Directory     string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type VerifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Non-empty if verification failed.
	Errors        []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GraphRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory containing holon.mod.
	Directory     string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphRequest) Reset() {
	*x = GraphRequest{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRequest) ProtoMessage() {}

func (x *GraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRequest.ProtoReflect.Descriptor instead.
func (*GraphRequest) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{10}
}

func (x *GraphRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type GraphResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The root holon path.
	Root string `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// All edges in the dependency graph.
	Edges         []*Edge `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphResponse) Reset() {
	*x = GraphResponse{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphResponse) ProtoMessage() {}

func (x *GraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphResponse.ProtoReflect.Descriptor instead.
func (*GraphResponse) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{11}
}

func (x *GraphResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *GraphResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{12}
}

func (x *Edge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Edge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Edge) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory containing holon.mod.
	Directory     string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type UpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dependencies that were updated.
	Updated       []*UpdatedDependency `protobuf:"bytes,1,rep,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateResponse) GetUpdated() []*UpdatedDependency {
	if x != nil {
		return x.Updated
	}
	return nil
}

type UpdatedDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	OldVersion    string                 `protobuf:"bytes,2,opt,name=old_version,json=oldVersion,proto3" json:"old_version,omitempty"`
	NewVersion    string                 `protobuf:"bytes,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatedDependency) Reset() {
	*x = UpdatedDependency{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedDependency) ProtoMessage() {}

func (x *UpdatedDependency) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedDependency.ProtoReflect.Descriptor instead.
func (*UpdatedDependency) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatedDependency) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdatedDependency) GetOldVersion() string {
	if x != nil {
		return x.OldVersion
	}
	return ""
}

func (x *UpdatedDependency) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

type VendorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory containing holon.mod.
	Directory     string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorRequest) Reset() {
	*x = VendorRequest{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorRequest) ProtoMessage() {}

func (x *VendorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorRequest.ProtoReflect.Descriptor instead.
func (*VendorRequest) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{16}
}

func (x *VendorRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type VendorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dependencies copied to .holon/.
	Vendored      []*Dependency `protobuf:"bytes,1,rep,name=vendored,proto3" json:"vendored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorResponse) Reset() {
	*x = VendorResponse{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorResponse) ProtoMessage() {}

func (x *VendorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorResponse.ProtoReflect.Descriptor instead.
func (*VendorResponse) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{17}
}

func (x *VendorResponse) GetVendored() []*Dependency {
	if x != nil {
		return x.Vendored
	}
	return nil
}

type CleanCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanCacheRequest) Reset() {
	*x = CleanCacheRequest{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanCacheRequest) ProtoMessage() {}

func (x *CleanCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanCacheRequest.ProtoReflect.Descriptor instead.
func (*CleanCacheRequest) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{18}
}

type CleanCacheResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path that was purged.
	CachePath     string `protobuf:"bytes,1,opt,name=cache_path,json=cachePath,proto3" json:"cache_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanCacheResponse) Reset() {
	*x = CleanCacheResponse{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanCacheResponse) ProtoMessage() {}

func (x *CleanCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanCacheResponse.ProtoReflect.Descriptor instead.
func (*CleanCacheResponse) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{19}
}

func (x *CleanCacheResponse) GetCachePath() string {
	if x != nil {
		return x.CachePath
	}
	return ""
}

type Dependency struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Path    string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Where this dependency was resolved to.
	CachePath     string `protobuf:"bytes,3,opt,name=cache_path,json=cachePath,proto3" json:"cache_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_api_rhizome_atlas_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_api_rhizome_atlas_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_api_rhizome_atlas_proto_rawDescGZIP(), []int{20}
}

func (x *Dependency) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Dependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Dependency) GetCachePath() string {
	if x != nil {
		return x.CachePath
	}
	return ""
}

var File_api_rhizome_atlas_proto protoreflect.FileDescriptor

const file_api_rhizome_atlas_proto_rawDesc = "" +
	"\n" +
	"\x17api/rhizome_atlas.proto\x12\x13holon.rhizome_atlas\"J\n" +
	"\vInitRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12\x1d\n" +
	"\n" +
	"holon_path\x18\x02 \x01(\tR\tholonPath\")\n" +
	"\fInitResponse\x12\x19\n" +
	"\bmod_file\x18\x01 \x01(\tR\amodFile\"X\n" +
	"\n" +
	"AddRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"N\n" +
	"\vAddResponse\x12?\n" +
	"\n" +
	"dependency\x18\x01 \x01(\v2\x1f.holon.rhizome_atlas.DependencyR\n" +
	"dependency\"A\n" +
	"\rRemoveRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x10\n" +
	"\x0eRemoveResponse\"+\n" +
	"\vPullRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\"I\n" +
	"\fPullResponse\x129\n" +
	"\afetched\x18\x01 \x03(\v2\x1f.holon.rhizome_atlas.DependencyR\afetched\"-\n" +
	"\rVerifyRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\"8\n" +
	"\x0eVerifyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\",\n" +
	"\fGraphRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\"T\n" +
	"\rGraphResponse\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12/\n" +
	"\x05edges\x18\x02 \x03(\v2\x19.holon.rhizome_atlas.EdgeR\x05edges\"D\n" +
	"\x04Edge\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"-\n" +
	"\rUpdateRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\"R\n" +
	"\x0eUpdateResponse\x12@\n" +
	"\aupdated\x18\x01 \x03(\v2&.holon.rhizome_atlas.UpdatedDependencyR\aupdated\"i\n" +
	"\x11UpdatedDependency\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vold_version\x18\x02 \x01(\tR\n" +
	"oldVersion\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\tR\n" +
	"newVersion\"-\n" +
	"\rVendorRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\"M\n" +
	"\x0eVendorResponse\x12;\n" +
	"\bvendored\x18\x01 \x03(\v2\x1f.holon.rhizome_atlas.DependencyR\bvendored\"\x13\n" +
	"\x11CleanCacheRequest\"3\n" +
	"\x12CleanCacheResponse\x12\x1d\n" +
	"\n" +
	"cache_path\x18\x01 \x01(\tR\tcachePath\"Y\n" +
	"\n" +
	"Dependency\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"cache_path\x18\x03 \x01(\tR\tcachePath2\xf4\x05\n" +
	"\x13RhizomeAtlasService\x12K\n" +
	"\x04Init\x12 .holon.rhizome_atlas.InitRequest\x1a!.holon.rhizome_atlas.InitResponse\x12H\n" +
	"\x03Add\x12\x1f.holon.rhizome_atlas.AddRequest\x1a .holon.rhizome_atlas.AddResponse\x12Q\n" +
	"\x06Remove\x12\".holon.rhizome_atlas.RemoveRequest\x1a#.holon.rhizome_atlas.RemoveResponse\x12K\n" +
	"\x04Pull\x12 .holon.rhizome_atlas.PullRequest\x1a!.holon.rhizome_atlas.PullResponse\x12Q\n" +
	"\x06Verify\x12\".holon.rhizome_atlas.VerifyRequest\x1a#.holon.rhizome_atlas.VerifyResponse\x12N\n" +
	"\x05Graph\x12!.holon.rhizome_atlas.GraphRequest\x1a\".holon.rhizome_atlas.GraphResponse\x12Q\n" +
	"\x06Update\x12\".holon.rhizome_atlas.UpdateRequest\x1a#.holon.rhizome_atlas.UpdateResponse\x12Q\n" +
	"\x06Vendor\x12\".holon.rhizome_atlas.VendorRequest\x1a#.holon.rhizome_atlas.VendorResponse\x12]\n" +
	"\n" +
	"CleanCache\x12&.holon.rhizome_atlas.CleanCacheRequest\x1a'.holon.rhizome_atlas.CleanCacheResponseB4Z2github.com/organic-programming/rhizome-atlas/protob\x06proto3"

var (
	file_api_rhizome_atlas_proto_rawDescOnce sync.Once
	file_api_rhizome_atlas_proto_rawDescData []byte
)

func file_api_rhizome_atlas_proto_rawDescGZIP() []byte {
	file_api_rhizome_atlas_proto_rawDescOnce.Do(func() {
		file_api_rhizome_atlas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rhizome_atlas_proto_rawDesc), len(file_api_rhizome_atlas_proto_rawDesc)))
	})
	return file_api_rhizome_atlas_proto_rawDescData
}

var file_api_rhizome_atlas_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_rhizome_atlas_proto_goTypes = []any{
	(*InitRequest)(nil),        // 0: holon.rhizome_atlas.InitRequest
	(*InitResponse)(nil),       // 1: holon.rhizome_atlas.InitResponse
	(*AddRequest)(nil),         // 2: holon.rhizome_atlas.AddRequest
	(*AddResponse)(nil),        // 3: holon.rhizome_atlas.AddResponse
	(*RemoveRequest)(nil),      // 4: holon.rhizome_atlas.RemoveRequest
	(*RemoveResponse)(nil),     // 5: holon.rhizome_atlas.RemoveResponse
	(*PullRequest)(nil),        // 6: holon.rhizome_atlas.PullRequest
	(*PullResponse)(nil),       // 7: holon.rhizome_atlas.PullResponse
	(*VerifyRequest)(nil),      // 8: holon.rhizome_atlas.VerifyRequest
	(*VerifyResponse)(nil),     // 9: holon.rhizome_atlas.VerifyResponse
	(*GraphRequest)(nil),       // 10: holon.rhizome_atlas.GraphRequest
	(*GraphResponse)(nil),      // 11: holon.rhizome_atlas.GraphResponse
	(*Edge)(nil),               // 12: holon.rhizome_atlas.Edge
	(*UpdateRequest)(nil),      // 13: holon.rhizome_atlas.UpdateRequest
	(*UpdateResponse)(nil),     // 14: holon.rhizome_atlas.UpdateResponse
	(*UpdatedDependency)(nil),  // 15: holon.rhizome_atlas.UpdatedDependency
	(*VendorRequest)(nil),      // 16: holon.rhizome_atlas.VendorRequest
	(*VendorResponse)(nil),     // 17: holon.rhizome_atlas.VendorResponse
	(*CleanCacheRequest)(nil),  // 18: holon.rhizome_atlas.CleanCacheRequest
	(*CleanCacheResponse)(nil), // 19: holon.rhizome_atlas.CleanCacheResponse
	(*Dependency)(nil),         // 20: holon.rhizome_atlas.Dependency
}
var file_api_rhizome_atlas_proto_depIdxs = []int32{
	20, // 0: holon.rhizome_atlas.AddResponse.dependency:type_name -> holon.rhizome_atlas.Dependency
	20, // 1: holon.rhizome_atlas.PullResponse.fetched:type_name -> holon.rhizome_atlas.Dependency
	12, // 2: holon.rhizome_atlas.GraphResponse.edges:type_name -> holon.rhizome_atlas.Edge
	15, // 3: holon.rhizome_atlas.UpdateResponse.updated:type_name -> holon.rhizome_atlas.UpdatedDependency
	20, // 4: holon.rhizome_atlas.VendorResponse.vendored:type_name -> holon.rhizome_atlas.Dependency
	0,  // 5: holon.rhizome_atlas.RhizomeAtlasService.Init:input_type -> holon.rhizome_atlas.InitRequest
	2,  // 6: holon.rhizome_atlas.RhizomeAtlasService.Add:input_type -> holon.rhizome_atlas.AddRequest
	4,  // 7: holon.rhizome_atlas.RhizomeAtlasService.Remove:input_type -> holon.rhizome_atlas.RemoveRequest
	6,  // 8: holon.rhizome_atlas.RhizomeAtlasService.Pull:input_type -> holon.rhizome_atlas.PullRequest
	8,  // 9: holon.rhizome_atlas.RhizomeAtlasService.Verify:input_type -> holon.rhizome_atlas.VerifyRequest
	10, // 10: holon.rhizome_atlas.RhizomeAtlasService.Graph:input_type -> holon.rhizome_atlas.GraphRequest
	13, // 11: holon.rhizome_atlas.RhizomeAtlasService.Update:input_type -> holon.rhizome_atlas.UpdateRequest
	16, // 12: holon.rhizome_atlas.RhizomeAtlasService.Vendor:input_type -> holon.rhizome_atlas.VendorRequest
	18, // 13: holon.rhizome_atlas.RhizomeAtlasService.CleanCache:input_type -> holon.rhizome_atlas.CleanCacheRequest
	1,  // 14: holon.rhizome_atlas.RhizomeAtlasService.Init:output_type -> holon.rhizome_atlas.InitResponse
	3,  // 15: holon.rhizome_atlas.RhizomeAtlasService.Add:output_type -> holon.rhizome_atlas.AddResponse
	5,  // 16: holon.rhizome_atlas.RhizomeAtlasService.Remove:output_type -> holon.rhizome_atlas.RemoveResponse
	7,  // 17: holon.rhizome_atlas.RhizomeAtlasService.Pull:output_type -> holon.rhizome_atlas.PullResponse
	9,  // 18: holon.rhizome_atlas.RhizomeAtlasService.Verify:output_type -> holon.rhizome_atlas.VerifyResponse
	11, // 19: holon.rhizome_atlas.RhizomeAtlasService.Graph:output_type -> holon.rhizome_atlas.GraphResponse
	14, // 20: holon.rhizome_atlas.RhizomeAtlasService.Update:output_type -> holon.rhizome_atlas.UpdateResponse
	17, // 21: holon.rhizome_atlas.RhizomeAtlasService.Vendor:output_type -> holon.rhizome_atlas.VendorResponse
	19, // 22: holon.rhizome_atlas.RhizomeAtlasService.CleanCache:output_type -> holon.rhizome_atlas.CleanCacheResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_rhizome_atlas_proto_init() }
func file_api_rhizome_atlas_proto_init() {
	if File_api_rhizome_atlas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rhizome_atlas_proto_rawDesc), len(file_api_rhizome_atlas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rhizome_atlas_proto_goTypes,
		DependencyIndexes: file_api_rhizome_atlas_proto_depIdxs,
		MessageInfos:      file_api_rhizome_atlas_proto_msgTypes,
	}.Build()
	File_api_rhizome_atlas_proto = out.File
	file_api_rhizome_atlas_proto_goTypes = nil
	file_api_rhizome_atlas_proto_depIdxs = nil
}
